[git]
repository_url = "git@gitlab.com:devops_stuff/gitops.git"
branch = "main"
poll_interval = 300
ssh_key_path = "/home/nemanja/.ssh/id_rsa"
quadlet_files_dir = "draw"

[podman]
quadlet_dir = "~/.config/containers/systemd"
backup_dir = "~/bin"

[metrics]
enabled = true
port = 8000
host = "0.0.0.0"

#[notifications]
#enabled = true
#email = {
#smtp_server = "smtp.example.com"
#    smtp_port = 587
#    username = "your-email@example.com"
#    password = "your-password"
#    recipients = ["admin@example.com"]
#}